clothcart/appclothcart/urls.py
from . import views
from django.urls import path

app_name='appclothcart'

urlpatterns = [
    path('',views.cloths,name='cloths'),
    path('cloth/<int:cloth_id>/',views.detail,name='detail'),
    path('add/',views.addcloth,name='addcloth'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

clothcart/clothcart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('appclothcart.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

clothcart/appclothcart/models.py
from django.db import models

# Create your models here.

class Cloth(models.Model):
    head= models.CharField(max_length=250)
    description = models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='images')

    def __str__(self):
        return self.head

clothcart/appclothcart/forms.py
from django import forms
from .models import Cloth

class ClothForm(forms.ModelForm):
    class Meta:
        model=Cloth
        fields=['head','description','year','image']

clothcart/appclothcart/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Cloth
from . forms import ClothForm




# Create your views here.



def cloths(request):
    database=Cloth.objects.all()

    return render(request,'intex.html',{'object':database})

def detail(request,cloth_id):
    cloth=Cloth.objects.get(id=cloth_id)

    return render(request,"details.html",{'cloth':cloth})


def addcloth(request):
    if request.method=="POST":
        head=request.POST.get('head')
        description = request.POST.get('description')
        year = request.POST.get('year')
        image = request.FILES['image']
        cloth=Cloth(head=head,description=description,year=year,image=image)
        cloth.save()

    return render(request,'add.html')

def update(request,id):
    cloth=Cloth.objects.get(id=id)
    form=ClothForm(request.POST or None,request.FILES,instance=cloth)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'cloth':cloth})

def delete(request,id):
    if request.method=='POST':
        cloth=Cloth.objects.get(id=id)
        cloth.delete()
        return redirect('/')
    return render(request, 'delete.html')

clothcart/templates/add.html
{% extends 'base.html' %}
{% block body %}


<style>
        label{width:300px;display:inline-block;margin:10px;}
        #form
        {text_align:center;border-radius:9px;
        width:500px;padding:19px;
        }
        #submit
        {width:100%;}
    </style>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h4>Add Cloth</h4>
    <fieldset>
    <label>Cloth Type</label>
  <input type="text" name="head" placeholder="Type Of Cloth"><br>
      <label>Enter Description</label>
  <input type="text" name="description" placeholder="description"><br>
      <label>Year</label>
  <input type="text" name="year"><br>
    <label>Upload Image</label>
    <input type="file" name="image" ><br>
    <input type="submit">
        </fieldset>
</form>

{% endblock %}

clothcart/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Clothcart</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
<!--    <img src="/docs/4.6/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">-->
    CLOTHcart
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

clothcart/templates/delete.html
{% extends 'base.html' %}
{% block body %}


<form method="POST">
    {% csrf_token %}
    <h3>Are You Sure Want TO Delete This Cloth</h3>
    <input  type="submit">
</form>

{% endblock %}

clothcart/templates/details.html
{% extends 'base.html' %}
{% block body %}



<div class="containser>">
    <div class="row">
        <div class="col-md-6">
            <img src="{{cloth.image.url}}">
        </div>
        <div class="col-md-6">
            <h1>{{cloth.head}}</h1><br>
            <br>
            <br>
            <h4>{{cloth.year}}</h4><br>
            <br>
            <h3>{{cloth.description}}</h3><br>
            <br>
            <a class="btn btn-warning" href="{% url 'appclothcart:update' cloth.id%}">update</a>
            <a class="btn btn-danger" href="{% url 'appclothcart:delete' cloth.id%}">delete</a>

        </div>
     </div>
</div>


{% endblock %}

clothcart/templates/intex.html
{% extends 'base.html' %}
{% block body %}

<br>
<a class="btn btn-warning" href="{% url 'appclothcart:addcloth' %}">Add Cloths</a>
<br>
<br>
<br>
<div class="containser>">
    <div class="row">
           {% for i in object %}
        <div class="col-md-3"><br><br><br>
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." width="300px" height="350px" >
  <div class="card-body">
    <h5 class="card-title"> {{i.head}}<br> <br>{{i.year}}</h5>
    <p class="card-text">{{i.description}}</p>

      <a href="{% url 'appclothcart:detail' i.id %}" class="btn btn-success">BUY NOW</a>
      <a href="{% url 'appclothcart:detail' i.id %}" class="btn btn-warning">ADD CART</a><br>
      <br>
      <a href="{% url 'appclothcart:detail' i.id %}" class="btn btn-primary">{{i.head}}</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>




{% endblock %}

clothcart/templates/update.html
{% extends 'base.html' %}
{% block body %}

<style>
        label{width:300px;display:inline-block;margin:10px;}
        #form
        {text_align:center;border-radius:9px;
        width:500px;padding:19px;
        }
        #submit
        {width:100%;}
    </style>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

{% endblock %}